#!/bin/bash
# ============================================
# Projeto: Auditoria Linux
# Autor: Vitor Moisés
# Objetivo:
# Ferramenta para consulta rápida de
# informações do sistema Linux.
# ============================================

echo '=============================='
echo '        AUDITORIA LINUX       '
echo '=============================='
echo
informacoes_sistema() {
	host=$(hostname)
	sistema=$(uname -o)
	kerne=$(uname -r)
	data=$(date '+%Y-%m-%d')
	hora=$(date '+%H:%M:%S')
	uptime=$(uptime -p)
echo '===================================================='
echo "             INFORMAÇÕES DO SISTEMA"
echo '===================================================='
echo "Hostname:.................. $host"
echo "Sistema operacional:......... $sistema"
echo "Kernel:..................... $kerne"
echo "Data:....................... $data"
echo "Hora:....................... $hora"
echo "Uptime:..................... $uptime"
echo '===================================================='
echo
}

processos_execucao(){
echo '============================================'
echo "             PROCESSOS EM EXECUÇÃO"
echo '============================================'
	quantidade_processos=$(ps -e --no-headers | wc -l)
	listar_processos=$(ps -eo pid:8,user:8,%cpu:8,%mem:8,comm --sort=-%cpu | head -n 6)
echo "Quantidade de processos em execução: $quantidade_processos"
echo
echo "   TOP 5 PROCESSOS POR CPU"
echo
echo "$listar_processos"
}

usuarios_logados(){
echo '==========================================='
echo "             USUÁRIOS LOGADOS"
echo '==========================================='
	# TODO: Ajustar a contagem de usuários após estudar
	# processamento de texto (grep, awk, sed ou cut).
	quantidade_usuarios=$(w | wc -l)
echo "Sessões ativas:"
echo
w
}

espaco_disco(){
echo '==========================================='
echo "             ESPAÇO EM DISCO"
echo '==========================================='
# Exibe apenas a partição principal (/)
df -h /
}

memoria_ram(){
echo '==========================================='
echo "             MEMÓRIA RAM"
echo '==========================================='
free -h

}

mostrar_relatorio(){
echo '==========================================='
echo "             RELATÓRIO DE GERAL"
echo '==========================================='
informacoes_sistema
processos_execucao
usuarios_logados
espaco_disco
memoria_ram

}

while true
do
	echo
	echo '1 - Informações do Sistema'
	echo '2 - Processos em Execução'
	echo '3 - Usuários Logados'
	echo '4 - Espaço em Disco'
	echo '5 - Memória RAM'
	echo '6 - Mostrar Relatório'
	echo '7 - Sair'
	echo
	echo -n 'Escolha: '
	read escolha
	echo

	case $escolha in
1)
	informacoes_sistema
	;;
2)
	processos_execucao
	;;
3)
	usuarios_logados
	;;
4)
	espaco_disco
	;;
5)
	memoria_ram
	;;
6)
	mostrar_relatorio
	;;
7)
	echo 'Encerrando sistema...'
	break
	;;
	esac
	done
