#!/bin/bash

echo '=============================='
echo '        AUDITORIA LINUX       '
echo '=============================='
echo
informacoes_sistema() {
	host=$(hostname)
	sistema=$(uname -o)
	kerne=$(uname -r)
	data=$(date '+%Y-%m-%d')
	hora=$(date '+%H:%M:%S')
	uptime=$(uptime -p)
echo '===================================================='
echo "Hostname:.................. $host"
echo "Sistema operacional:......... $sistema"
echo "Kernel:..................... $kerne"
echo "Data:....................... $data"
echo "Hora:....................... $hora"
echo "Uptime:..................... $uptime"
echo '===================================================='
}

processos_execucao(){

echo '===================================================='
echo "             PROCESSOS EM EXECUÇÃO"
echo '===================================================='
	quanridade_processos=$(ps -e --no-headers | wc -l)
	listar_processos=$(ps -eo pid:8,user:8,%cpu:8,%mem:8,comm --sort=-%cpu | head -n 6)
echo
echo "Quantidade de processos em execução: $quanridade_processos"
echo
echo "   TOP 5 PROCESSOS POR CPU"
echo
echo "$listar_processos"
}

usuarios_logados(){

echo '===================================================='
echo "             USUÁRIOS LOGADOS"
echo '===================================================='
	

}

espaco_disco(){
	:
}

memoria_ram(){
	:
}

salvar_relatorio(){
	:
}

mostrar_relatorio(){
	:
}

while true
do
	echo
	echo '1 - Informações do Sistema'
	echo '2 - Processos em Execução'
	echo '3 - Usuários Logados'
	echo '4 - Espaço em Disco'
	echo '5 - Memória RAM'
	echo '6 - Salvar Relatório'
	echo '7 - Mostrar Relatório'
	echo '8 - Sair'
	echo
	echo -n 'Escolha: '
	read escolha
	echo

	case $escolha in
1)
	informacoes_sistema
	;;
2)
	processos_execucao
	;;
3)
	usuarios_logados
	;;
4)
	espaco_disco
	;;
5)
	memoria_ram
	;;
6)
	salvar_relatorio
	;;
7)
	mostrar_relatorio
	;;
8)
	echo 'Encerrando sistema...'
	break
	;;
	esac
	done
